### ISSUE TITLE
make all in web sample

### ISSUE THREAD

**Issue by jcarvalhogo** [earlephilhower/esp-quick-toolchain#27]
I am having a problem in the make all of the HttpServer_WebSockets project.
Make al with old compiler:

HttpServer_WebSockets: Invoking 'clean' for Esp8266 (debug) architecture
Cleaning application...
> make all

HttpServer_WebSockets: Invoking 'all' for Esp8266 (debug) architecture
/Applications/Xcode.app/Contents/Developer/usr/bin/make components application

Building /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/samples/HttpServer_WebSockets/out/Esp8266/debug/lib/clib-App-eac50efbb93c10976f20a184ac75adca.a
C+ /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/samples/HttpServer_WebSockets/app/CUserData.cpp
C+ /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/samples/HttpServer_WebSockets/app/application.cpp
CC /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/Components/rboot/appcode/rboot-overrides.c
CC /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/Components/rboot/rboot/appcode/rboot-api.c
CC /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/Components/rboot/rboot/appcode/rboot-bigflash.c
AS /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/Arch/Esp8266/Components/gdbstub/appcode/gdbstub-entry.S
C+ /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/Arch/Esp8266/Components/gdbstub/appcode/gdb_hooks.cpp
AR /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/samples/HttpServer_WebSockets/out/Esp8266/debug/lib/clib-App-eac50efbb93c10976f20a184ac75adca.a
E2 /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/samples/HttpServer_WebSockets/out/Esp8266/debug/firmware/rboot.bin
Prepare libmain
LDGEN out/Esp8266/debug/build/rom0.ld
HttpServer_WebSockets: Linking out/Esp8266/debug/build/app_0.out
/opt/esp-open-sdk/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/10.2.0/../../../../xtensa-lx106-elf/bin/ld: /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/out/Esp8266/debug/lib/clib-Sming-38587903b650da883c01137a2aa4ed9a.a(HttpServerConnection.o): in function `_ZNK9ObjectMapI6String12HttpResourceE7indexOfERKS0_':
/Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/Core/Data/ObjectMap.h:238: undefined reference to `abort'
/opt/esp-open-sdk/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/10.2.0/../../../../xtensa-lx106-elf/bin/ld: /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/out/Esp8266/debug/lib/clib-Sming-38587903b650da883c01137a2aa4ed9a.a(HttpServerConnection.o): in function `_ZN16HttpHeaderFields12findOrCreateERK6String':
/Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/Core/Network/Http/HttpHeaderFields.h:120: undefined reference to `abort'
/opt/esp-open-sdk/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/10.2.0/../../../../xtensa-lx106-elf/bin/ld: /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/out/Esp8266/debug/lib/clib-Sming-38587903b650da883c01137a2aa4ed9a.a(HttpServerConnection.o): in function `_ZN20HttpServerConnection17onHeadersCompleteERK11HttpHeaders':
/Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/Core/Network/Http/HttpServerConnection.cpp:107: undefined reference to `abort'
/opt/esp-open-sdk/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/10.2.0/../../../../xtensa-lx106-elf/bin/ld: /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/out/Esp8266/debug/lib/clib-sming-arch-0e98c5bb1d92e9d6d3a431aa55fe6ee7.a(StationImpl.o): in function `_ZN6VectorI7BssInfoEixEj':
/Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/Wiring/WVector.h:490: undefined reference to `abort'
/opt/esp-open-sdk/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/10.2.0/../../../../xtensa-lx106-elf/bin/ld: /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/out/Esp8266/debug/lib/clib-sming-arch-0e98c5bb1d92e9d6d3a431aa55fe6ee7.a(StationImpl.o): in function `_ZNK6VectorI7BssInfoE9elementAtEj':
/Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/Wiring/WVector.h:256: undefined reference to `abort'
/opt/esp-open-sdk/xtensa-lx106-elf/bin/../lib/gcc/xtensa-lx106-elf/10.2.0/../../../../xtensa-lx106-elf/bin/ld: /Volumes/DEV-PART/iot/espressif/SmingHub/Sming/samples/HttpServer_WebSockets/out/Esp8266/debug/lib/clib-App-eac50efbb93c10976f20a184ac75adca.a(application.o):/Volumes/DEV-PART/iot/espressif/SmingHub/Sming/Sming/Wiring/WVector.h:501: more undefined references to `abort' follow
collect2: error: ld returned 1 exit status
make[1]: *** [out/Esp8266/debug/build/app_0.out] Error 1
make: *** [all] Error 2

**Comment by earlephilhower** [comment]
Are you sure you're using this toolchain?  `esp-open-sdk` shown in the logs is another project AFAIK.

Barring that, I'd need some sort of MCVE to reproduce this.  On the ESP8266 Arduino core (which this toolchain is used for) the CI system isn't seeing any issues...
