### ISSUE TITLE
[feature request] save `A0` when `-Og` is enabled

### ISSUE THREAD

**Issue by d-a-v** [earlephilhower/esp-quick-toolchain#44]
[ per proposal](https://github.com/esp8266/Arduino/pull/8837#issuecomment-1410343314)

Cc: @jjsuwa-sys3175 @mhightower83

**Comment by jjsuwa-sys3175** [comment]
The patch should look something like this ([xtensa-Enforce-return-address-saving-when-Og-is-spec.patch](https://github.com/earlephilhower/esp-quick-toolchain/files/10552833/xtensa-Enforce-return-address-saving-when-Og-is-spec.patch)).

**Comment by jjsuwa-sys3175** [comment]
The patch has been merged into gcc/master,
[xtensa: Enforce return address saving when -Og is specified](https://github.com/gcc-mirror/gcc/commit/a804419c89db9e1c0b99e772dda6c95095bab0bf)

**Comment by jjsuwa-sys3175** [comment]
Of course, this patch will be included in the forthcoming toolchain :)

**Comment by earlephilhower** [comment]
@jjsuwa-sys3175 is this in #37?  Can we close this issue (the PR to update to the new toolchain is waiting in the Arduino repo now)

**Comment by jjsuwa-sys3175** [comment]
> @jjsuwa-sys3175 is this in #37? Can we close this issue (the PR to update to the new toolchain is waiting in the Arduino repo now)

Yes.
