### ISSUE TITLE
All `make` commands require `GHUSER` and `GHTOKEN` to be set

### ISSUE THREAD

**Issue by slonopotamus** [earlephilhower/esp-quick-toolchain#46]
Subj. I'd expect these would only be needed for `make upload`.

**Comment by earlephilhower** [comment]
This is by design.  The standard use case (actually the only one) is to run this to build a full toolchain and upload for a new Arduino release.  I'd rather have it fail immediately after hitting return then after an hour of compute time.

**Comment by slonopotamus** [comment]
Okay
