### ISSUE TITLE
Release installs only x86_64 binaries on Apple Silicon macs

### ISSUE THREAD

**Issue by vitkabele** [earlephilhower/esp-quick-toolchain#49]
Hello,
I tried to build a project for ESP8266 on M2 Mac with platformio (via esphome), but it turns out that the release only contains binaries for x86_64 architecture. This seems like a mistake since [this page](https://registry.platformio.org/tools/platformio/toolchain-xtensa/compatibility) says that the relase should be compatible with arm64 macos (if that does not mean via the Rosetta mechanism ofc).

**Comment by earlephilhower** [comment]
Sorry, you do need to use Rosetta to run it.

It is presently not possible to cross-build a GCC compiler for the Apple Darwin ARM line (only clang was running).  If someone contributes needed patches to [osxcross](https://github.com/tpoechtrager/osxcross) and GNU GCC it could be done.  But until then, Rosetta will be required.
